# Use root/pestillo as user/password credentials
version: '3.8'

services:

  mongo:
    image: mongo
    command: [--auth]
    ports:
      - 27017:27017
    volumes:
      - ./mongo/mongodbdata:/data/db
      - ./mongo/initdb/:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pestillo

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pestillo
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_DATABASE=admin
    ports:
      - '8081:8081'

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - DATABASE_HOST=postgres
      - POSTGRES_USER=javier
      - POSTGRES_PASSWORD=pestillo
      - POSTGRES_DB=prison

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080


