# Use root/pestillo as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    command: [--auth]
    ports:
      - 27017:27017
    volumes:
      - ./mongodbdata:/data/db
      - ./initdb/:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pestillo

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pestillo
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_DATABASE=admin
    ports:
      - '8081:8081'